### ISSUE TITLE
Add Set method

### ISSUE THREAD

**Issue by bouk** [rdleal/go-priorityq#1]
Hi there, thanks for this package it's exactly what I was looking for!

I want to Push an item if it's not in the queue or Update it otherwise. Might be nice to add a 'Set' method that doesn't return an error but that Push or Update depending on whether the item already exists

**Comment by rdleal** [comment]
Hi @bouk . I'm happy you find this package useful for you.

You suggestion makes sense, and seems convenient. Just to make sure the addition of the new method solves your problem: today you can do this by guarding the operations under a `pq.Contains` condition:
```go
if pq.Contains(k) {
        pq.Update(k, v)
} else {
        pq.Push(k, v)
}
```
The downside of this is that between the calls to `pq.Contains` and either `pq.Push` or `pq.Update`, another goroutine might potentially have added or removed the `k` key from the queue, thus potentially causing `pq.Push` or `pq.Update` to return error in case the `k` key was added or the `k` key was removed, respectively. By having the `Set` method, we can guard those operations under a single lock, and guarantee the atomicity of them.

Is that the problem you are facing or the reason you are suggestion this improvement?

**Comment by bouk** [comment]
Yes, that's exactly why I was thinking it would be nice to have it implemented in the package itself!

**Comment by rdleal** [comment]
@bouk I've added the new method in a branch called `set-method`. If you want to give it a try:
```sh
go get github.com/rdleal/go-priorityq@set-method
```

I should have it merged to main in a couple of days, just finishing some more testing and doc stuff on it.

Here is a working example:
```go
cmp := func(a, b int) bool {
	return a < b
}
pq := kpq.NewKeyedPriorityQueue[string](cmp)

// Insert elements onto the priority queue
pq.Push("second", 42)
pq.Push("first", 30)
pq.Push("last", 50)

// Updates an element
pq.Set("last", 20)

k, v, ok := pq.Pop()
if !ok {
	log.Fatal("priority queue is empty")
}

fmt.Printf("Key: %q, Value: %d\n", k, v) // Key: "last", Value: 20

// Inserts a new element
pq.Set("new_first", 1)
k, v, ok = pq.Pop()
if !ok {
	log.Fatal("priority queue is empty")
}

fmt.Printf("Key: %q, Value: %d\n", k, v) // Key: "new_first", Value: 1
```

**Comment by rdleal** [comment]
@bouk Method `Set` pushed out to `main` branch. Thanks for the patience and for using and bringing feedback to this package.
